name: 🐛 Bug Report
description: Create a report to help us improve VoxFlow
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Use the latest version of VoxFlow
        - Test with a minimal reproduction case

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Component
      description: Which component is affected?
      options:
        - Frontend (React UI)
        - Backend (Node.js API)
        - Python Service (Voxtral)
        - Audio Processing
        - WebSocket Connection
        - File Upload/Download
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Critical (App crashes, data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌐 Environment
      description: |
        Please provide details about your environment:
      value: |
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - Browser: [e.g. Chrome 120, Safari 17, Firefox 119]
        - Node.js: [e.g. 18.17.0]
        - Python: [e.g. 3.11.0]
        - VoxFlow Version: [e.g. 1.0.0]
        - Device: [e.g. MacBook Pro M4, Windows Desktop]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs
      description: |
        Please provide any relevant error logs or console output.
        Tip: You can attach images or paste logs here.
      placeholder: |
        Paste error logs here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        You can drag and drop images here.

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: |
        Add any other context about the problem here.
        - Does this happen consistently?
        - Are there any workarounds?
        - When did this start happening?

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I am using the latest version of VoxFlow
          required: true
        - label: I have provided a clear description and steps to reproduce
          required: true
        - label: I have included relevant logs and environment details
          required: true